### ISSUE TITLE
Vacation/Special/Course Leaves

### ISSUE THREAD

**Issue by deanscovill** [ryanscovill/surrey-app#11]
Need the following:

1. Month/date picks
2. Need leave stat when click on individual in calendar.  Right now it looks like:

{{vacation.employee}}

Category 
{{vacation.section}} 

Type 
{{vacation.category}} 

Hours 
{{vacation.hours}} 

Start Date 
{{vacation.start_date}} 

End Date 
{{vacation.end_date}} 

3.  When "Vacation" is chosen require a pop up that states, "If required, I will return to work under emergency situation:  YES      NO

4.  Provide an option to cancel vacation, special leave or course and removed from calendar.  Would I be able to see tracking of this? 

Thx

**Comment by ryanscovill** [comment]
1. Completed
2. Completed
3. Completed, Option in form
4. Completed, yes, there is a history of all activities that happen to leave requests.
