### ISSUE TITLE
New Column in Employee Section

### ISSUE THREAD

**Issue by deanscovill** [ryanscovill/surrey-app#12]
I need a new column labelled "Classification".  To be located between EOCP and Vehicle headings on Employees section.

Thanks

**Comment by ryanscovill** [comment]
There is a column called "Classification" for employee currently located after Employee # with values such as trades 1, foreman, etc..

**Comment by deanscovill** [comment]
Sorry, I meant to add “EOCP” in front of Classification.  This is a government classification.

Thx

**Comment by ryanscovill** [comment]
Ok, so then is the field is called Government Classification or EOCP Classification?

**Comment by deanscovill** [comment]
EOCP Classification

Thx

**Comment by ryanscovill** [comment]
Is this field required?

**Comment by deanscovill** [comment]
yep
