### ISSUE TITLE
Permit Yonatan and Grant Access

### ISSUE THREAD

**Issue by deanscovill** [ryanscovill/surrey-app#4]
For login please add:

Yonatan.Yohannes@surrey.ca
GMHeska@surrey.ca

What password should they use?

Read only access to program.  I will retain Admin Rights at this time.

Thanks,
Dad

**Comment by ryanscovill** [comment]
Same password.  All users are 'admin' and no permissions are set up currently.

**Comment by ryanscovill** [comment]
They can log in

**Comment by deanscovill** [comment]
Just to confirm their ID is there email and password is the same one we are using?

Thx
Dad

**Comment by ryanscovill** [comment]
Yes, that's correct

**Comment by deanscovill** [comment]
Thanks
