### ISSUE TITLE
Add Ken Poon

### ISSUE THREAD

**Issue by deanscovill** [ryanscovill/surrey-app#8]
Add Ken Poon for access to app.  KPoon@surrey.ca

Is the email address case sensitive?  If Ken enters kpoon@surrey.ca will this work also?

Thx

**Comment by ryanscovill** [comment]
It's not case sensitive, any variation will work

**Comment by deanscovill** [comment]
Thanks

**Comment by ryanscovill** [comment]
However, I'll need to set a password for him in order to login

**Comment by deanscovill** [comment]
I just spoke with Ken.  He wants to hold off in gaining access for now until the app is live in City of Surrey.  Sorry, leave this request for now.  Let me know if you haven’t heard from Roger by the end of the week and Ken will give him a call.

Thanks,
Dad

**Comment by ryanscovill** [comment]
Ok, will do
